# 실전문제
## 큰수의 법칙
- 풀이시간 30분
- 소요시간 00분

In [25]:
N,M,K = 5,7,3
numbers = [2,4,5,4,6]

numbers.sort(reverse = True)
n = numbers[0:2]
answer = 0

if n[0] == n[1]:
    answer = n[0]*K
else:
    num = [n[0]]*K+[n[1]]
    length = len(num)

    for i in range(M):
        answer += num[i%length]

answer 

41

In [28]:
n,m,k = map(int,input().split())
data = list(map(int,input().split()))

data.sort()

first = data.pop()
second = data.pop()
result = 0 

while True:
    for i in range(k):
        if m == 0:
            break
        result += first
        m -= 1
    if m == 0:
        break
    result += second
    m -= 1
print(result)


46


## 숫자카드게임
- 제한시간 00분
- 소요시간 00분

In [31]:
from numpy import random
random.randint(9,size= (5,5))

array([[0, 6, 1, 0, 5],
       [5, 2, 0, 6, 1],
       [5, 7, 0, 6, 7],
       [4, 6, 3, 1, 1],
       [5, 2, 6, 3, 8]])

In [39]:
n = 2
m = 4 

arr = random.randint(9,size= (n,m))
print(arr)

num = []
for i in range(len(arr)):
    minnum = min(arr[i])
    num.append(minnum)
max(num)

[[0 6 7 1]
 [0 1 1 7]]


0

## 1이 될때까지
- 제한시간 00분
- 소요시간 00분

In [44]:
n = 25 
k = 3

count = 0


while n != 1:
    if n%k == 0:
        n = n//k
        count += 1
    else : 
        n -=1 
        count += 1
print(count)

6


# 기출문제
## 모험가길드
- 풀이시간 30분
- 소요시간 00분

In [70]:
n = 5
members = [4,4,1,4,4]
members.sort()

count = 0
group = 0 
for i in members:
    count +=1 
    if count >= i:
        group +=1
        count = 0 

group

2

### 코멘트

## 곱하기 혹은 더하기
- 풀이시간 30분
- 소요시간 00분

In [107]:
import random
# n = random.randint(1,21)
# numbers = random.choices(range(0,10),k=n)
numbers = '9990999999'
numbers = [int(k) for k in numbers]
numbers.sort(reverse =True)

max_int = 2000000000
result = 1 

for i in numbers:
    if i !=0 :
        result *= i
        if result > max_int:
            result //= i 
            result += i 
    else :
        print(i,'else')
        result += i
result

0 else


387420489

In [111]:
numbers = '9990999999'
numbers = [int(k) for k in numbers]

result = numbers[0]
for i in range(1,len(numbers)):
    num = numbers[i]
    if num<=1 or result<=1:
        result += num
    else:
        result *=num
result

387420489

## 문자열 뒤집기
- 풀이시간 30분
- 소요시간 00분

In [148]:
string = '000110001101'

count0 = 0
count1 = 0

if string[0] == '1':
    count1 +=1
else:
    count0 +=1

for i in range(len(string)-1):
    if string[i] != string[i+1]:
        if string[i+1] == '1':
            count1 +=1
        else:
            count0 +=1
print(count0,count1)

3 3


## 만들수 없는 금액
- 풀이시간 30분
- 소요시간 00분

In [153]:
coins = [3,2,1,1,9]
coins.sort()

target = 1 
for i in coins:
    if target < i:
        break
    target += i 
target

8

## 볼링공 고르기
- 풀이시간 30분
- 소요시간 00분

In [159]:
from itertools import combinations

balls = [1,5,4,3,2,4,5,2]

combi = []
for i in combinations(balls,2):
    if i[0] != i[1]:
        combi.append(i)
len(combi)

25

In [190]:
balls = [1,5,4,3,2,4,5,2]
balls.sort()
st ={}
for i in balls:
    st[i] = st.get(i,0) + 1

answer =0 
for j in range(1,len(st)+1):
    case = st[j] * sum(list(st.values())[j:])
    answer += case
print(answer)


25


In [195]:
n = 8
m = 5 
balls = [1,5,4,3,2,4,5,2]

arr = [0] * (m +1)
for x in balls:
    arr[x] +=1 
result = 0

for i in range(1,m+1):
    n -=arr[i]
    result += arr[i]*n
print(result)

25
