In [2]:
import numpy as np
from tqdm import tqdm

# 1.Numpy

행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리할 수 있도록 지원하는 파이썬의 라이브러리

references: 
- [numpy](https://numpy.org/doc/stable/reference/index.html#reference)
- [cs231 numpy](https://cs231n.github.io/python-numpy-tutorial/)
- [Python For Data Science Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

<br>

numpy 특징 <br>
- 파이썬 리스트에 비해 빠르고, 메모리 효율적
- 반복문 없이 배열에 대한 처리 지원
- 다양한 기능 제공
<br>
<br>

numpy 기능 <br>
- 1. shape: numpy dimension
- 2. ndim: shape에서 얼마나 나오는지
- 3. dtype: numpy 원소의 데이터 타입

## 1.1 배열 생성

파이썬 배열 -> numpy array

In [49]:
a = list(range(10))
np.array(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

### 1.1.1 기본 배열 생성

#### arange
일정 범위의 배열을 생성 <br>
python의 range와 유사 <br>
단, arange는 실수 사용 가능 <br>

> 주의 <br>
np.arange(-3, 3, 0.5, dtype=int) <br>
array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

<br>

사용법
```python
x = np.arange(0, 10)
x = np.arange(-5, 5, 0.5)
```

In [6]:
list(range(0, 10, 0.5)) # 소수 step 불가

TypeError: 'float' object cannot be interpreted as an integer

In [11]:
print(list(range(0, 10)))
print(np.arange(0, 10, 0.5))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
list(range(0, 10)) + 1  # 리스트에 각 원소를 1씩 증가시키기 위해 +1을 사용할 수 없음

TypeError: can only concatenate list (not "int") to list

In [21]:
np.arange(0, 10) + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
(np.arange(0, 10) + 1) / (np.arange(0, 10) * 2) # numpy의 element-wise 연산

C:\Users\user\AppData\Local\Temp\ipykernel_13320\2787778438.py:1: RuntimeWarning: divide by zero encountered in true_divide
  (np.arange(0, 10) + 1) / (np.arange(0, 10) * 2)


array([       inf, 1.        , 0.75      , 0.66666667, 0.625     ,
       0.6       , 0.58333333, 0.57142857, 0.5625    , 0.55555556])

In [44]:
# rank: 1~100등까지 등수가 담긴 array
# 1 ~20:  1, 
# 21~40:  2, 
# 41~60:  3,
# 61~80:  4,
# 81~100: 5
# 값을 부여하는 코드

In [32]:
# solution 1
ranks = np.random.choice(np.arange(1, 101), size=100)

grades = []
for rank in ranks:
    if rank > 80:
        grades.append(5)
    elif rank > 60:
        grades.append(4)
    elif rank > 40:
        grades.append(3)
    elif rank > 20:
        grades.append(2)
    else:
        grades.append(1)

In [41]:
# solution 2
ranks = np.random.choice(np.arange(1, 101), size=100)

ranks.sort()

ranks[:20] = 1
ranks[20:40] = 2
ranks[40:60] = 3
ranks[60:80] = 4
ranks[80:] = 5

In [48]:
# solution 3
ranks = np.random.choice(np.arange(1, 101), size=100)
((ranks-1) // 20) + 1

array([1, 3, 5, 5, 4, 1, 2, 2, 4, 1, 4, 1, 3, 2, 4, 1, 2, 1, 3, 4, 1, 4,
       1, 2, 1, 5, 1, 4, 1, 4, 3, 4, 2, 5, 4, 4, 1, 5, 1, 1, 3, 2, 5, 5,
       3, 1, 3, 2, 5, 2, 4, 2, 4, 4, 5, 4, 3, 2, 3, 5, 4, 5, 4, 3, 5, 1,
       2, 1, 2, 3, 5, 2, 5, 3, 1, 5, 4, 2, 3, 5, 4, 4, 3, 1, 3, 3, 4, 1,
       3, 3, 4, 2, 4, 1, 3, 2, 5, 5, 5, 4], dtype=int32)

#### linspace

arange와 유사 <br>
start와 stop를 주어진 숫자 만큼 분할

<br>

사용법
```python
x = np.linspace(2, 3, num=5)
x = np.linspace(2, 3, num=5, endpoint=False)    # 끝 점 미포함 
```

In [58]:
print(np.linspace(2, 3, num=5))
print(np.linspace(2, 3, num=5, endpoint=False))

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]


#### eye

대각행렬이 1이고 나머지가 0인 행렬 생성 <br>
k를 이용하여 1의 위치를 조정할 수 있음 <br>
<br>

사용법
```python
x = np.eye(10)    # np.identity와 동일
x = np.eye(10, k =1)
```

In [65]:
np.eye(5, k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

#### zeros

shape을 입력하면 모든 값이 0인 해당 shape에 맞는 배열 생성 <br>

사용법
```python
x = np.zeros(5)
x = np.zeros((5, 2), dtype=float)
```

In [68]:
print(np.zeros(5))
print(np.zeros((3, 5, 2)))

[0. 0. 0. 0. 0.]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


#### ones

shape을 입력하면 모든 값이 1인 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.ones(5)
x = np.ones((5, 2), dtype=float)
```

In [69]:
print(np.ones(5))
print(np.ones((3, 5, 2)))

[1. 1. 1. 1. 1.]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


#### full

shape과 숫자를 입력하면 입력한 숫자로 찬 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.full(5, np.inf)
x = np.full((5, 2), np.nan)
```

In [73]:
print(np.full(5, 3))
print(np.full((3, 5, 2), np.nan))

[3 3 3 3 3]
[[[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]]

 [[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]]

 [[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]]]


#### tril

lower triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
```

In [80]:
print(np.tril([[1,2,3],[4,5,6],[7,8,9]]))
print(np.tril([[1,2,3],[4,5,6],[7,8,9]], -1))

[[1 0 0]
 [4 5 0]
 [7 8 9]]
[[0 0 0]
 [4 0 0]
 [7 8 0]]


#### triu

upper triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)
```

In [76]:
np.triu([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

### 1.1.2 랜덤 배열 생성

#### random

균등분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.random(size=(2, 3))    # size: dim
```

In [81]:
np.random.random(size=(2, 3))

array([[0.13831088, 0.42605079, 0.47333869],
       [0.25413433, 0.92538181, 0.70936186]])

#### randint

지정한 범위 내에서 임의의 수 생성

사용법
```python
x = np.random.randint(0, 10, size=(5,2))    # size: dim
```

In [95]:
np.random.randint(1, 46, size=6)

array([43, 30, 11,  8, 19, 37])

In [94]:
np.random.randint(0, 10, size=(5, 2))

array([[9, 1],
       [9, 3],
       [9, 0],
       [4, 4],
       [2, 2]])

In [98]:
temp = np.random.randint(1, 46, size=(5, 6))

In [112]:
[6, 14, 15, 19, 41, 21] == [6, 14, 15, 19, 21, 41]  # 리스트의 모든 원소와 값이 일치할 때 True

False

In [106]:
temp[0] == [6, 14, 15, 19, 21, 41]  # numpy는 element-wise 연산

array([False, False, False, False, False, False])

In [ ]:
# 로또 6 14 15 19 21 41 (1045)
# 함수 만들기
#   input: 돈
#   output: 몇 장 당첨

def lotto(money, win_numbers):
    numbers = np.random.randint(1, 46, size=(money//1000, 6))
    win_count = 0

    for number in tqdm(numbers):
        number.sort()

        if list(number) == win_numbers:
            win_count += 1
    
    return win_count

#### normal

정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.normal(loc=0, scale=1, size=(2, 3))
# loc: 평균
# scale: 분산
# size: dim
```

In [114]:
np.random.normal(loc=10, scale=100, size=(5, 2))

array([[ -59.92868489,   49.86038112],
       [ -18.1466934 ,  -62.36941532],
       [  87.85447989,    9.0989153 ],
       [ -43.20366551, -111.18768382],
       [-127.00674771, -141.91322731]])

#### randn

표준정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.randn(2, 3)
```

In [119]:
np.random.randn(2, 3, 4)

array([[[ 0.94361428,  0.13560481, -0.11116748, -0.38327758],
        [-1.00724377, -1.46633718, -0.59749728,  0.10921364],
        [ 0.71420097, -0.12557745, -0.39207586,  0.40817977]],

       [[ 0.74430442,  1.19828779, -0.29428278, -0.57610323],
        [ 0.08881513,  1.17980253, -1.18434799, -0.04600854],
        [-0.57025355, -1.18297103,  0.50329936,  0.13620005]]])

## 1.2 배열 조작

### 1.2.1 배열 결합

#### concatenate

두 배열을 결합 <br>
<br>

사용법 
```python
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)
np.concatenate([a, b], axis=0)
np.concatenate([a, b], axis=1)
```

In [122]:
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)

In [125]:
np.concatenate([a, b], axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [126]:
np.concatenate([a, b], axis=1)

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11]])

### 1.2.2 배열 분할

#### array_split

주어진 배열을 분할 <br>
<br>

사용법
```python
x = np.arange(9.0)
np.split(x, 3)
np.split(x, [3, 5, 6, 10])
```

In [135]:
x = np.arange(9)
print(np.split(x, 3))
print(np.split(x, [3, 5, 6, 10]))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8]), array([], dtype=int32)]


### 1.2.3 차원 변경

#### reshape

배열의 모양을 원하는 형태로 바꿈 <br>
단, 바꾸는 배열의 차원 곱은 원 배열의 차원 곱과 일치해야 함 <br>
<br>

사용법
```python
x = np.arange(30)
x.reshape(5, 6)
```


In [142]:
np.arange(30).reshape(3, 2, 5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

#### flatten

배열을 1차원 배열로 바꿈 <br>
<br>
사용법 <br>
```python
x = np.arange(30).reshape(2, 5, 3)
x.flatten()
```

In [144]:
np.arange(30).reshape(3, 2, 5).flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### squeeze

불필요한 차원을 제거 <br>
즉, 길이가 0인 차원을 제거 <br>
<br>

사용법
```python
x = np.arange(10).reshape(10, 1, 1)
x.squeeze()
```

In [151]:
np.arange(30).reshape(1, 1, 1, 1, 30).squeeze()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### expand_dims

차원 추가 <br>
<br>

사용법
```python
x = np.arange(10)
np.expand_dims(x, 0)
```

In [156]:
x = np.arange(10)
np.expand_dims(x, 0)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 1.2.4 모양 변경

##### roll

배열을 입력한 수 만큼 이동 <br>
<br>

사용법
```python
x = np.arange(10)
np.roll(x, 2)
```

```python
x = np.reshape(x, (2, 5))
np.roll(x, 1)
np.roll(x, -1, axis=0)
np.roll(x, -1, axis=1)
```

In [160]:
x = np.arange(10)
print(np.roll(x, 2))
print(np.roll(x, -2))

[8 9 0 1 2 3 4 5 6 7]
[2 3 4 5 6 7 8 9 0 1]


In [165]:
x = np.arange(10).reshape(2, 5)
print(x)
print(np.roll(x, 1, axis=0))
print(np.roll(x, 1, axis=1))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[5 6 7 8 9]
 [0 1 2 3 4]]
[[4 0 1 2 3]
 [9 5 6 7 8]]


##### flip

지정된 축을 기준으로 배열을 뒤집음 <br>
<br>

사용법

```python
x = np.arange(10).reshape(5, 2)
np.flip(x, 0)
```


In [172]:
x = np.arange(20).reshape(4, 5)
print(x)
print('--------------------')
print(np.flip(x, axis=0))   # x[::-1, :]
print('--------------------')
print(np.flip(x, axis=1))   # x[:,::-1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
--------------------
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
--------------------
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]


### 1.2.5 축 변경

#### swapaxes

두 축의 위치를 지정하여 변경 <br>
<br>

사용법
```python
x = np.arange(100).reshape(5, 2, 10)
x.swapaxis(0, 2)    # 0 <-> 2
```

#### transpose

여러 축의 위치를 변경 <br>
transpose에 들어가는 인자는 축의 순서 <br>
<br>

사용법

```python
x = np.arange(100).reshape(5, 2, 10)
x.transpose(0, 2, 1)    # 1번 축과 2번 축을 바꿈
x.transpose(2, 0, 1)    # 2->0, 0->1, 1->2
```

### 1.2.6 배열 정렬

#### sort

주어진 축을 기준으로 배열 정렬 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.sort(axis=1)
x
```



In [182]:
x = np.random.randint(0, 10, (5, 4))
print(x)
print('---------')
x.sort(axis=0)
print(x)
print('---------')
x.sort(axis=1)
print(x)

[[9 7 3 5]
 [7 4 4 8]
 [2 3 5 5]
 [1 9 8 4]
 [5 4 9 6]]
---------
[[1 3 3 4]
 [2 4 4 5]
 [5 4 5 5]
 [7 7 8 6]
 [9 9 9 8]]
---------
[[1 3 3 4]
 [2 4 4 5]
 [4 5 5 5]
 [6 7 7 8]
 [8 9 9 9]]


#### argsort

주어진 축을 기준으로 정렬된 배열의 인덱스 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.argsort(axis=1)
```


In [185]:
x = np.random.randint(0, 10, 10)
print(x)
print(x.argsort())

[5 1 4 1 0 8 4 5 2 4]
[4 1 3 8 2 6 9 0 7 5]


### 1.2.7 기타

##### unique

배열 내의 중복값 제거 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
np.unique(x, axis=0)
```

In [186]:
x = np.random.randint(0, 10, 10)
print(x)
print(np.unique(x))

[4 7 9 3 4 2 3 0 1 1]
[0 1 2 3 4 7 9]


#### nan_to_num

배열 내의 nan 값을 특정 숫자로 변환 <br>
<br>

사용법
```python
x = np.full((3, 4), np.nan)
np.nan_to_num(x, nan=1)


In [191]:
x = np.full((2, 3), np.nan)
np.nan_to_num(x, nan=-1)

array([[-1., -1., -1.],
       [-1., -1., -1.]])

#### trim_zeros

배열 내의 0값을 제거 <br>
<br>

사용법
```python
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trin_zeros(x, trim='f')    # 앞의 0만 제거
np.trin_zeros(x, trim='b')    # 뒤의 0만 제거
np.trin_zeros(x, trim='fb')   # 앞뒤 0 제거
```

In [197]:
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
print(np.trim_zeros(x, trim='f'))    # 앞의 0만 제거
print(np.trim_zeros(x, trim='b'))    # 뒤의 0만 제거
print(np.trim_zeros(x, trim='fb'))   # 앞뒤 0 제거

[1 2 3 0 2 1 0]
[0 0 0 1 2 3 0 2 1]
[1 2 3 0 2 1]


stride_tricks

배열을 주어진 윈도우 만큼 분할 <br>
<br>

사용법
```python
x = np.arange(10)
y = np.lib.stride_tricks.sliding_window_view(x, 3)
```

In [200]:
x = np.arange(10)
print(x)
print(
    np.lib.stride_tricks.sliding_window_view(x, 5)
)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]


## 1.3 배열 탐색

### argmax

축을 기준으로 배열에서 최댓걊의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmax(x)
np.argmax(x, axis=0)
```

In [204]:
x = np.random.randint(0, 10, size=(2, 3))
print(x)
print('----------------------')
print(np.argmax(x))
print('----------------------')
print(np.argmax(x, axis=0))
print('----------------------')
print(np.argmax(x, axis=1))

[[1 6 5]
 [4 5 7]]
----------------------
5
----------------------
[1 0 1]
----------------------
[1 2]


### argmin

축을 기준으로 배열에서 최솟걊의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmin(x)
np.argmin(x, axis=0)
```



In [206]:
x = np.random.randint(0, 10, size=(2, 3))
print(x)
print('----------------------')
print(np.argmin(x))
print('----------------------')
print(np.argmin(x, axis=0))
print('----------------------')
print(np.argmin(x, axis=-1))

[[3 1 4]
 [0 4 6]]
----------------------
3
----------------------
[1 0 0]
----------------------
[1 0]


### where

특정 조건에 맞는 값의 index 반환 또는 값 변환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.where(x < 5)    # 조건을 만족하는 값의 인덱스 반환
np.where(x < 5, 1, 0)    # x가 5보다 작은 값은 1, 그렇지 않으면 0
```

In [215]:
x = np.random.randint(1, 10, 10)
print(x)
print(x[np.where(x < 5)])   # x[x < 5]
print(np.where(x < 5, 1, -1))

[4 5 2 3 1 1 2 9 3 1]
[4 2 3 1 1 2 3 1]
[ 1 -1  1  1  1  1  1 -1  1  1]


### extract

특정 조건에 맞는 값을 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.extract(x > 2, x)
```

In [216]:
x = np.random.randint(1, 10, 10)
print(x)
print(x[np.extract(x > 5, x)])

[2 7 9 9 9 1 7 6 7 5]
[6 5 5 5 6 7 6]


##  1.4 배열 연산

### matmul

행렬 곱 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))

np.matmul(x, y)
x @ y
```

In [219]:
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))

print(x)
print(y)
print(np.matmul(x, y))
print(x @ y)

[[8 8]
 [3 2]]
[[8 4]
 [3 2]]
[[88 48]
 [30 16]]
[[88 48]
 [30 16]]


### eigen

eigenvalue, eigenvector 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.eig(x)
```



In [220]:
x = np.random.randint(0, 10, size=(2, 2))
np.linalg.eig(x)

(array([8.54138127, 2.45861873]),
 array([[ 0.54426202, -0.21504559],
        [ 0.83891528,  0.97660401]]))

### det

배열의 행렬식을 구함 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.det(x)
```

In [221]:
x - np.random.randint(0, 10, size=(2, 2))
print(x)
print(np.linalg.det(x))

[[7 1]
 [7 4]]
21.0


### trace
대각원소의 합 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.trace(x)
```

In [223]:
x - np.random.randint(0, 10, size=(2, 2))
print(x)
print(np.trace(x))

[[7 1]
 [7 4]]
11


### solve

선형 방정식의 해를 반환 <br>
<br>


사용법
```python
#  x_0 + 2*x_1 = 1
# 3x_0 + 5*x_1 = 2:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
np.linalg.solve(a, b)
```

In [227]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])

np.linalg.solve(a, b)

array([-1.,  1.])

inv

선형 방정식의 해를 반환 <br>
<br>


사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.inv(x)
```

In [224]:
x - np.random.randint(0, 10, size=(2, 2))
print(x)
print(np.linalg.inv(x))

[[7 1]
 [7 4]]
[[ 0.19047619 -0.04761905]
 [-0.33333333  0.33333333]]


## 1.5 통계 함수

#### ptp

축별 최댓값 - 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.ptp(axis=0)
```

In [229]:
x = np.arange(12).reshape(4, 3)
print(x)
print('----------------')
print(x.ptp(axis=0))
print('----------------')
print(x.ptp(axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
----------------
[9 9 9]
----------------
[2 2 2 2]


#### median

축별 중앙값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
np.median(x, axis=0)
```

In [231]:
x = np.arange(12).reshape(4, 3)
print(x)
print('----------------')
print(np.median(x, axis=0))
print('----------------')
print(np.median(x, axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
----------------
[4.5 5.5 6.5]
----------------
[ 1.  4.  7. 10.]


### sum

축별 합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
x.sum(axis=1)
```

In [232]:
x = np.arange(12).reshape(4, 3)
print(x)
print('----------------')
print(x.sum(axis=0))
print('----------------')
print(x.sum(axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
----------------
[18 22 26]
----------------
[ 3 12 21 30]


### average

축별 가중합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
np.average(x, weights=[0.5, 0.3, 0.2])
```

In [236]:
x = np.array([3, 4, 5])
np.average(x, weights=[0.5, 0.3, 0.2])

3.7

### mean

축별 평균 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.mean(axis=1)
```

In [237]:
x = np.arange(12).reshape(4, 3)
print(x)
print('----------------')
print(x.mean(axis=0))
print('----------------')
print(x.mean(axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
----------------
[4.5 5.5 6.5]
----------------
[ 1.  4.  7. 10.]


### min

축별 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.min(axis=1)
```

In [238]:
x = np.arange(12).reshape(4, 3)
print(x)
print('----------------')
print(x.min(axis=0))
print('----------------')
print(x.min(axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
----------------
[0 1 2]
----------------
[0 3 6 9]


### max

축별 최댓값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.max(axis=1)
```

In [239]:
x = np.arange(12).reshape(4, 3)
print(x)
print('----------------')
print(x.max(axis=0))
print('----------------')
print(x.max(axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
----------------
[ 9 10 11]
----------------
[ 2  5  8 11]


### std
축별 표준편차 산출 <br>
<br>

사용법

```python
x = np.arange(12).reshape(4,3)
x.std(axis=1)
```

In [4]:
x = np.arange(12).reshape(4, 3)
print(x)
print('-----------------')
print(x.std(axis=0))
print(x.std(axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
-----------------
[3.35410197 3.35410197 3.35410197]
[0.81649658 0.81649658 0.81649658 0.81649658]


### cov

공분산 산출 <br>
<br>

사용법
```python
x = np.random.rand(25).reshape(5, 5)
np.cov(x)
```

In [5]:
x = np.random.rand(25).reshape(5, 5)
print(np.cov(x))

[[ 8.54893398e-02  7.17641789e-02  5.81135762e-02 -4.12145603e-02
  -5.16257805e-02]
 [ 7.17641789e-02  7.06205895e-02  7.78014097e-02 -2.64522182e-02
  -4.81200115e-02]
 [ 5.81135762e-02  7.78014097e-02  1.59710337e-01  1.68870268e-05
  -3.81158382e-02]
 [-4.12145603e-02 -2.64522182e-02  1.68870268e-05  3.74549869e-02
   1.81234008e-02]
 [-5.16257805e-02 -4.81200115e-02 -3.81158382e-02  1.81234008e-02
   3.79729535e-02]]
